//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teacher
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Idteach { get; set; }
    }
}
